-- Drop table

-- DROP TABLE dbo.usuario

CREATE TABLE usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(50) NOT NULL,
	apellido varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	contrasenha varchar(35) NOT NULL,
	idinstitucion int8 NOT NULL DEFAULT 1,
	idrol int8 NULL,
	ultmodificacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fechaalta timestamp NOT NULL DEFAULT now(),
	CONSTRAINT usuario_institucion_fk FOREIGN KEY (idinstitucion) REFERENCES institucion(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT usuario_rol_fk FOREIGN KEY (idrol) REFERENCES rol(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
